- name: add user and create ssh key
  user: name={{ deploy_user }} shell=/bin/bash append=true

- name: create .ssh/ dir for deploy user
  file:
    path: '{{ deploy_user_home_dir }}/.ssh'
    state: directory
    owner: '{{ deploy_user }}'
    group: '{{ deploy_user_group }}'
    mode: 0700

- name: copy authorized keys for deploy user
  copy:
    remote_src: True
    src: '/root/.ssh/authorized_keys'
    dest: '{{ deploy_user_home_dir }}/.ssh'
    owner: '{{ deploy_user }}'
    group: '{{ deploy_user_group }}'
    mode: 0600
  tags: auth_keys

- name: Creates deploy_directory directory
  file:
    path: '{{ deploy_directory }}/shared/config'
    state: directory
    recurse: yes
    owner: '{{ deploy_user }}'
    group: '{{ deploy_user_group }}'
    mode: 0755

- name: copy some config files, needed for deploy and start application
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'environment.example', dest: '{{ deploy_directory }}/shared/config/environment.{{ app_stage }}' }
