- name: common conditions
  hosts: all
  gather_facts: false
  user: root

  roles:
    - install_packages
    - yarn
    - nodejs
    - user
    - postgresql
    - nginx

- name: Install ruby for single user via rvm support
  hosts: all
  user: root

  roles:
    - {
        role: rvm.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-{{ ruby_version }}'],
        rvm1_user: '{{ deploy_user }}',
        rvm1_install_flags: --auto-dotfiles --user-install,
        # Use available libs, fail if some are missing.
        rvm1_autolib_mode: 2
      }
